# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
                ('ParentInformationSourceID', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='spearapp.InformationSource', verbose_name='Information Source Parent ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organised_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpearPhishingIncidencenumber', models.CharField(max_length=100, verbose_name='Spearphishing_Incidence_Number')),
                ('IncidenceDescription', models.TextField(verbose_name='incidence_description')),
                ('MoreInfor', models.CharField(max_length=300, verbose_name='More_Infor')),
                ('EntryDateofAddition', models.DateTimeField(auto_now_add=True)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
                ('InformationSourceID', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='spearapp.InformationSource', verbose_name='Org Parent ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpearIncidenceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spear_Attack_Type', models.IntegerField(default=1, verbose_name=((1, 'Email'), (2, 'Misleading-Advertisement'), (3, 'Misleading-Office-Memo'), (4, 'Misleading-Information'), (5, 'Email-With-Attachment'), (6, 'PDF-As-Attachment'), (7, 'Email-With-DLL'), (8, 'Adobe-Flash-Player'), (9, 'Torjan'), (10, 'Clone-Site-Link'), (11, 'Social-Media-Request-Message')))),
                ('Attackorigincountry', models.CharField(max_length=222, verbose_name='Attack_Origin_Country')),
                ('Attacktargetcountry', models.CharField(max_length=222, verbose_name='Attack_Target_Country')),
                ('Attacktargetindustry', models.CharField(max_length=222, verbose_name='Attack_Target_Industry')),
                ('Attacktargetbrand', models.CharField(max_length=222, verbose_name='Attack_Target_Brand')),
                ('Attacktargetindiviual', models.CharField(max_length=222, verbose_name='Attack_Target')),
                ('Attackoriginip', models.IntegerField(verbose_name='Attack_Origin')),
                ('Aim_Ofthe_Attack', models.IntegerField(default=1, verbose_name=((1, 'Finacial'), (2, 'Extortion'), (3, 'Corporate Espionage'), (4, 'Political-Espionage'), (5, 'Miltariry-Espionage'), (6, 'Militarily-Espionage'), (7, 'Insider-Attacker-Sabotage'), (8, 'Business-Continuity-Disruption'), (9, 'Compromise-Data-Integrity'), (10, 'Data-Leakage'), (11, 'Other-Unknown-Motive'), (12, 'Cyber-Terrorism'), (13, 'Cyber-Bulling-Trolling')))),
                ('Attacktopleveldomain', models.CharField(max_length=111, verbose_name='Attack_Top-Level-Domain')),
                ('Attackduration', models.FloatField(max_length=12, verbose_name='Attack_Duration')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
                ('SpearPhishingIncidencenumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spearapp.Organised_Information', verbose_name='From Organised_Information ')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
                ('ParentSubjectID', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='spearapp.Subjects', verbose_name='Subject Parent ID')),
            ],
        ),
        migrations.AddField(
            model_name='organised_information',
            name='SubjectID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spearapp.Subjects', verbose_name='Parent ID'),
        ),
    ]
