# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0002_auto_20160624_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsource',
            name='Name',
            field=models.CharField(default='brica.de', max_length=100, verbose_name='InformationSource'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attackoriginip',
            field=models.IntegerField(verbose_name='AttackOrigininatingIP'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attacktargetbrand',
            field=models.CharField(max_length=222, verbose_name='AttackTargetBrand/Company'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='NameOfSubject',
            field=models.CharField(default='Spear Phishing', max_length=100, verbose_name='NameofSubject'),
        ),
    ]
