# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0003_auto_20160624_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='NameOfSubject',
            new_name='NameOfTheSubject',
        ),
    ]
