# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0005_auto_20160624_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='The_Analysis',
        ),
    ]
