# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0008_auto_20160624_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attackduration',
            field=models.FloatField(default=1, max_length=12, verbose_name='Attack Duration'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attackoriginip',
            field=models.CharField(default='0.0.0.0.0', max_length=21, verbose_name='AttackOrigininatingIP'),
        ),
    ]
