# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0010_auto_20160624_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attacktargetindustry',
            field=models.IntegerField(choices=[(1, 'Banking'), (2, 'Financial'), (3, 'Petroleum'), (4, 'Energy'), (5, 'Celebrity'), (6, 'Govt Office'), (7, 'Political Party'), (8, 'Construction'), (9, 'Computer'), (10, 'Agriculture'), (11, 'Pharma'), (12, 'Health'), (13, 'Telcom'), (14, 'Water'), (15, 'MassMedia'), (16, 'Food'), (17, 'Rail'), (18, 'Transport'), (19, 'Non-Financial-Organisation'), (20, 'No Available')], default='Not Known', verbose_name='Which Industry'),
        ),
        migrations.AlterField(
            model_name='the_analysis',
            name='AttackTargetIndustryStatistics',
            field=models.IntegerField(choices=[(1, 'Banking'), (2, 'Financial'), (3, 'Petroleum'), (4, 'Energy'), (5, 'Celebrity'), (6, 'Govt Office'), (7, 'Political Party'), (8, 'Construction'), (9, 'Computer'), (10, 'Agriculture'), (11, 'Pharma'), (12, 'Health'), (13, 'Telcom'), (14, 'Water'), (15, 'MassMedia'), (16, 'Food'), (17, 'Rail'), (18, 'Transport'), (19, 'Non-Financial-Organisation'), (20, 'No Available')], verbose_name='Which Industry'),
        ),
    ]
