# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0011_auto_20160624_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='spearincidencedetail',
            name='Content_As_Spear',
            field=models.CharField(default='Not Known', max_length=400, verbose_name='Words/Sentences'),
        ),
    ]
