# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0013_auto_20160625_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organised_Information',
            new_name='OrganisedInformation',
        ),
    ]
