# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0014_auto_20160625_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='attackaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttackAim', models.CharField(default='Financial', max_length=100, verbose_name='Aim of SpearAttack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='attackmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttackMethod', models.CharField(default='Email', max_length=100, verbose_name='Method of Attack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry_Name', models.CharField(default='Financial', max_length=100, verbose_name='Industry Under Attack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='topeleveldomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopeLevelDomain_Name', models.CharField(default='Financial', max_length=100, verbose_name='Aim of SpearAttack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organisedinformation',
            name='EntryDateofAddition',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Aim_Ofthe_Attack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spearapp.attackaim', verbose_name='Aim of the Spear Phishing Attack'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attack_Top_Level_Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spearapp.topeleveldomain', verbose_name='Top Level Domain'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attacktargetindustry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spearapp.industry', verbose_name='Which Industry'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Spear_Attack_Method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spearapp.attackmethod', verbose_name='SpearAttack Method'),
        ),
    ]
