# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0016_auto_20160627_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_under_attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Under_Attack', models.CharField(default='Financial', max_length=100, verbose_name='Aim of SpearAttack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='origin_country_attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin_Country_Attacker', models.CharField(default='Financial', max_length=100, verbose_name='Aim of SpearAttack')),
                ('LastUpdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
