# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0017_country_under_attack_origin_country_attacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Aim_Ofthe_Attack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spearapp.attackaim', verbose_name='Aim SpearAttack'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attack_Top_Level_Domain',
            field=models.ForeignKey(default='US', on_delete=django.db.models.deletion.CASCADE, to='spearapp.topeleveldomain', verbose_name='TopLevelDomain'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attackorigincountry',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.CASCADE, to='spearapp.origin_country_attacker', verbose_name='Origin_country_attacker'),
        ),
        migrations.AlterField(
            model_name='spearincidencedetail',
            name='Attacktargetcountry',
            field=models.ForeignKey(default='USA', on_delete=django.db.models.deletion.CASCADE, to='spearapp.country_under_attack', verbose_name='Country_under_attack'),
        ),
    ]
