# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spearapp', '0018_auto_20160627_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackmethod',
            name='AttackMethod',
            field=models.CharField(default='Email', max_length=100, verbose_name='Method of SpearAttack'),
        ),
        migrations.AlterField(
            model_name='country_under_attack',
            name='Country_Under_Attack',
            field=models.CharField(default='Financial', max_length=100, verbose_name='Country Under SpearAttack'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='Industry_Name',
            field=models.CharField(default='Financial', max_length=100, verbose_name='Industry Under SpearAttack'),
        ),
        migrations.AlterField(
            model_name='origin_country_attacker',
            name='Origin_Country_Attacker',
            field=models.CharField(default='Financial', max_length=100, verbose_name='Origin of SpearAttack'),
        ),
    ]
